DROP TABLE repo;
DROP TABLE commits;

CREATE TABLE repo(version INTEGER, hash VARCHAR2(256) PRIMARY KEY, filesystem BLOB);
CREATE TABLE commits(version INTEGER, hash VARCHAR2(256) PRIMARY KEY, patch BLOB);
